# Find players transferring from Hungarian top division to Premier League directly

Using data from https://www.kaggle.com/datasets/cbhavik/football-transfers-from-199293-to-202122-seasons

In [1]:
import pandas as pd

In [2]:
transfers = pd.read_csv("./data/premier-league.csv")
transfers.head()

,club_name,player_name,age,position,club_involved_name,fee,transfer_movement,transfer_period,fee_cleaned,league_name,year,season
0,Middlesbrough FC,Tommy Wright,26.0,Left Winger,Leicester,€910Th.,in,Summer,0.91,Premier League,1992,1992/1993
1,Middlesbrough FC,Jonathan Gittens,28.0,defence,Southampton,€250Th.,in,Summer,0.25,Premier League,1992,1992/1993
2,Middlesbrough FC,Chris Morris,28.0,Right-Back,Celtic,?,in,Summer,NaN,Premier League,1992,1992/1993
3,Middlesbrough FC,Ben Roberts,17.0,Goalkeeper,Boro U18,-,in,Summer,NaN,Premier League,1992,1992/1993
4,Middlesbrough FC,Andy Todd,17.0,Centre-Back,Boro U18,-,in,Summer,NaN,Premier League,1992,1992/1993

Limit to "in" transfers

In [20]:
transfers_in = transfers[transfers["transfer_movement"] == "in"].copy()
transfers_in.head()

,club_name,player_name,age,position,club_involved_name,fee,transfer_movement,transfer_period,fee_cleaned,league_name,year,season
0,Middlesbrough FC,Tommy Wright,26.0,Left Winger,Leicester,€910Th.,in,Summer,0.91,Premier League,1992,1992/1993
1,Middlesbrough FC,Jonathan Gittens,28.0,defence,Southampton,€250Th.,in,Summer,0.25,Premier League,1992,1992/1993
2,Middlesbrough FC,Chris Morris,28.0,Right-Back,Celtic,?,in,Summer,NaN,Premier League,1992,1992/1993
3,Middlesbrough FC,Ben Roberts,17.0,Goalkeeper,Boro U18,-,in,Summer,NaN,Premier League,1992,1992/1993
4,Middlesbrough FC,Andy Todd,17.0,Centre-Back,Boro U18,-,in,Summer,NaN,Premier League,1992,1992/1993

Let's see what clubs people come in from

In [21]:
transfers_in[
    transfers_in["club_involved_name"].str.lower().str.strip().str.contains("ferenc")
]

,club_name,player_name,age,position,club_involved_name,fee,transfer_movement,transfer_period,fee_cleaned,league_name,year,season
7841,West Bromwich Albion,Zoltán Gera,25.0,Central Midfield,Ferencváros,€2.25m,in,Summer,2.25,Premier League,2004,2004/2005
16787,Everton FC,Muhamed Besic,21.0,Defensive Midfield,Ferencváros,€4.80m,in,Summer,4.80,Premier League,2014,2014/2015

OK looks like Hungarian clubs are in but annoyingly they don't have a "league from" field.

Let's manually find all Hungarian clubs because apparently we have time on our hands?!

In [ ]:
# transfers_in["club_involved_name"] = (
#    transfers_in["club_involved_name"].str.strip().str.lower()
# )

in_clubs = sorted(transfers_in["club_involved_name"].unique())

pd.DataFrame(in_clubs).to_csv("./data/clubs.csv", index=False)

These look like the only ones in the data.

Let's pretty print them!

In [24]:
hungarian_clubs = [
    "debrecen",
    "diósgyőr",
    "eto fc győr",
    "fehérvár",
    "ferencváros",
    "mtk budapest",
    "mtk u19",
    "újpest fc",
    "zalaegerszeg",
]

hungarian_transfers = (
    transfers_in[
        transfers_in["club_involved_name"].str.lower().str.strip().isin(hungarian_clubs)
    ]
    .sort_values(["year", "player_name"])
    .copy()
)

transfer_years = hungarian_transfers["year"].unique()

for year in transfer_years:
    print(f"{year}")
    for row in hungarian_transfers[hungarian_transfers["year"] == year].itertuples():
        print(f"\t{row.player_name} to {row.club_name} from {row.club_involved_name}")

2004
	Márton Fülöp to Tottenham Hotspur from MTK Budapest
	Sándor Torghelle to Crystal Palace from MTK Budapest
	Zoltán Gera to West Bromwich Albion from Ferencváros
2006
	Péter Máté to Reading FC from Debrecen
	Tamás Priskin to Watford FC from ETO FC Győr
2007
	András Simon to Liverpool FC from MTK U19
	Krisztián Németh to Liverpool FC from MTK Budapest
	Tamás Kádár to Newcastle United from Zalaegerszeg
2008
	Péter Gulácsi to Liverpool FC from MTK U19
	Péter Kurucz to West Ham United from Újpest FC
2009
	Péter Kurucz to West Ham United from Újpest FC
	Scott Malone to Wolverhampton Wanderers from Újpest FC
2014
	Muhamed Besic to Everton FC from Ferencváros
	Márkó Futács to Leicester City from Diósgyőr
2019
	Danilo Pantic to Chelsea FC from Fehérvár
2021
	Bendegúz Bolla to Wolverhampton Wanderers from Fehérvár